/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        'display': ['Space Grotesk', 'sans-serif'],
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Hanken Grotesk', 'sans-serif'],
        'label': ['Space Mono', 'monospace'],
        'mono': ['Space Mono', 'monospace'],
      },
      colors: {
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f9fbe5',
        'surface': '#f9fbe5',
        'on-primary-fixed': '#171e00',
        'on-surface': '#1a1d10',
        'on-tertiary-fixed-variant': '#004f54',
        'background': '#f9fbe5',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e2e4cf',
        'outline-variant': '#c5c9ac',
        'inverse-on-surface': '#f1f2dc',
        'error': '#ba1a1a',
        'secondary-fixed': '#ffdbd1',
        'secondary': '#ac2e00',
        'tertiary-fixed-dim': '#00dbe9',
        'on-tertiary-container': '#00777f',
        'on-surface-variant': '#444932',
        'tertiary-container': '#bbf9ff',
        'surface-container': '#eef0da',
        'on-secondary-fixed': '#3b0900',
        'primary-fixed': '#caf300',
        'error-container': '#ffdad6',
        'on-primary-container': '#5f7400',
        'primary-container': '#d4ff00',
        'inverse-surface': '#2f3223',
        'surface-container-highest': '#e2e4cf',
        'primary': '#536600',
        'surface-container-low': '#f4f5df',
        'on-background': '#1a1d10',
        'surface-tint': '#536600',
        'inverse-primary': '#b0d500',
        'tertiary': '#006970',
        'primary-fixed-dim': '#b0d500',
        'on-secondary-container': '#fffbff',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#002022',
        'on-secondary-fixed-variant': '#862200',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#3e4c00',
        'secondary-container': '#d73b00',
        'secondary-fixed-dim': '#ffb5a0',
        'outline': '#757a60',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e8ead4',
        'on-primary': '#ffffff',
        'surface-dim': '#dadcc6',
        'tertiary-fixed': '#7df4ff',
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '800' }],
        'display-lg-mobile': ['48px', { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-lg': ['40px', { lineHeight: '1.1', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.1', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.0', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.0', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
      },
      spacing: {
        'base': '4px',
        'xs': '8px',
        'sm': '16px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'grid-gutter': '16px',
        'grid-margin': '24px',
      },
      boxShadow: {
        'neo': '4px 4px 0px 0px rgba(0,0,0,1)',
        'neo-heavy': '6px 6px 0px 0px rgba(0,0,0,1)',
        'neo-sm': '2px 2px 0px 0px rgba(0,0,0,1)',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        shake: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(-2deg)' },
          '75%': { transform: 'rotate(2deg)' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
      animation: {
        marquee: 'marquee 20s linear infinite',
        float: 'float 3s ease-in-out infinite',
        shake: 'shake 0.3s ease-in-out',
        'slide-up': 'slide-up 0.4s ease-out',
      },
    },
  },
  plugins: [],
};
